ISPP-Grupo-10/cocemfe-sevilla

codenfe_sevilla/codenfe_sevilla/settings.py
codenfe_sevilla/professionals/models.py
codenfe_sevilla/professionals/validators.py

Añade un validador de contraseñas seguras y modifica Professional para que herede correctamente del modelo usuario de User

Añade contraseñas seguras a Professional

---

codenfe_sevilla/documents/templates/update_pdf.html

Actualizada la interfaz para la modificación de documentos

Sprint1 frontend modificar documentos

---

cocemfe_sevilla/documents/forms.py
cocemfe_sevilla/documents/models.py
cocemfe_sevilla/documents/templates/upload_pdf.html
cocemfe_sevilla/documents/tests.py
cocemfe_sevilla/documents/views.py

Se han creado tests para la subida de los pdfs.
Se ha corregido el estado en la creación automática de documentos
Se ha corregido la validación del tipo pdf

Test subida pdf y corrige errores estado documento y validación de pdf

---

cocemfe_sevilla/documents/templates/upload_pdf.html
cocemfe_sevilla/documents/views.py
cocemfe_sevilla/professionals/templates/professional_list.html
cocemfe_sevilla/professionals/views.py

Se han corregido errores en la visualización de botones para los usuarios, en la visualización de subir pdfs(salía el administrador como profesional) y en la visualización de los propios pdfs siendo administrador.

Fix: Corrección de errores y restricciones

---

cocemfe_sevilla/documents/forms.py
cocemfe_sevilla/documents/templates/list_pdf.html
cocemfe_sevilla/documents/templates/upload_pdf.html
cocemfe_sevilla/documents/views.py

Se han corregido errores en la edición de documentos para que no aparezca el administrador como profesional.
Así mismo se han corregido los permisos para que en el módulo de documentos tan solo el administrador pueda editar y eliminar los mismos.
También se han deshabilitado botones que estaban visibles para los usuarios cuando no debería ser así.

Fix: Corregidos errores de permisos en varios módulos

---

cocemfe_sevilla/documents/forms.py
cocemfe_sevilla/documents/models.py
cocemfe_sevilla/documents/templates/update_pdf.html
cocemfe_sevilla/documents/views.py

Se añade la posibilidad de actualizar el estado en la pantalla 'Modificar Documento' y se han corregido los estados del modelo 'Document'

Sprint1 detalles mejorados documentos

---

cocemfe_sevilla/base/templates/base.html
cocemfe_sevilla/organizations/views.py
cocemfe_sevilla/professionals/forms.py
cocemfe_sevilla/professionals/models.py
cocemfe_sevilla/professionals/templates/create_request.html
cocemfe_sevilla/professionals/templates/list_requests.html
cocemfe_sevilla/professionals/templates/professional_list.html
cocemfe_sevilla/professionals/templates/registration/login.html
cocemfe_sevilla/professionals/templates/update_request.html
cocemfe_sevilla/professionals/urls.py
cocemfe_sevilla/professionals/views.py

Sprint2 login

---

cocemfe_sevilla/suggestions/models.py

Se ha añadido un nuevo atributo Relevance de tipo enumerado al modelo suggestions

Feature/113 creación enumerado relevance

---

cocemfe_sevilla/documents/templates/update_pdf.html
cocemfe_sevilla/documents/views.py

Corrige la edición de documentos
closes #156

#156 Corrige la edición de documentos

---

cocemfe_sevilla/documents/templates/list_pdf.html
cocemfe_sevilla/documents/templates/view_pdf.html

Al realizar el merge desde visual no me salen las actualizaciones asi que lo hago de manera manual desde aqui

Merge de aportaciones a votaciones

---

cocemfe_sevilla/base/templates/base.html
cocemfe_sevilla/documents/templates/list_pdf.html
cocemfe_sevilla/organizations/templates/organizations_list.html
cocemfe_sevilla/organizations/views.py
cocemfe_sevilla/professionals/templates/list_chats.html
cocemfe_sevilla/professionals/templates/list_requests.html
cocemfe_sevilla/professionals/templates/professional_detail.html
cocemfe_sevilla/professionals/templates/registration/login.html
cocemfe_sevilla/professionals/urls.py
cocemfe_sevilla/professionals/views.py

Actualización de la estética de la web, aún quedan algunas vistas que serán abordadas en el siguiente Sprint.

fix: nueva estetica pagina web

---

cocemfe_sevilla/professionals/forms.py
cocemfe_sevilla/professionals/templates/update_password.html
cocemfe_sevilla/professionals/tests.py
cocemfe_sevilla/professionals/urls.py
cocemfe_sevilla/professionals/views.py

Para acceder a la pantalla hay que ir a professionals/change_password. Esto es debido a que esta pantalla está conectada a la de perfil de usuario, la cual no está creada todavía y es otra manera. De manera provisional lo he implementado así.

Feature/240 Añadido Backend Edición Contraseña

---

cocemfe_sevilla/professionals/forms.py

Se ha incorporado manejo de los formularios para hacer que las contraseñas sean únicas

fix: correos de profesionales unicos - Closes #275

---

cocemfe_sevilla/chat_messages/models.py
cocemfe_sevilla/documents/urls.py
cocemfe_sevilla/organizations/tests.py
cocemfe_sevilla/professionals/forms.py
cocemfe_sevilla/professionals/tests.py
cocemfe_sevilla/professionals/urls.py

Rama donde se solucionan todos los fallos menores, como pequeños errores del codacy o de funcionalidad del subgrupo 3

fix/272 Solucionar Problemas Subgrupo 3

---

cocemfe_sevilla/base/templates/base.html
cocemfe_sevilla/professionals/templates/professional_list.html

Implementación de la primera versión del footer, con enlaces a las políticas de privacidad.

Feature/237 Footer

---

cocemfe_sevilla/calendars/models.py
cocemfe_sevilla/calendars/templates/eventos.html
cocemfe_sevilla/documents/templates/update_pdf.html
cocemfe_sevilla/documents/views.py

Corrige la edición de documentos para que no de fallo cuando no hay alguna fecha definida.
También añade limite de caracteres a titulo y descripcion del evento
close #290

Hotfix/290 bug fallo en edición de documentos

---

cocemfe_sevilla/professionals/forms.py
cocemfe_sevilla/professionals/templates/email/verification_email.html
cocemfe_sevilla/professionals/views.py

Se ha solucionado el problema en el que no era posible iniciar sesion con una cuenta creada.
En la versión anterior, se generaban 3 contraseñas en el Forms, ahora solo genera una, y he modificado un poco la manera en la que se genera

fix: Solucionado problema inicio sesion Closes #301

---

cocemfe_sevilla/chat_messages/consumers.py
cocemfe_sevilla/chat_messages/routing.py
cocemfe_sevilla/chat_messages/templates/chatPage.html
cocemfe_sevilla/chat_messages/urls.py
cocemfe_sevilla/chat_messages/views.py
cocemfe_sevilla/cocemfe_sevilla/asgi.py
cocemfe_sevilla/cocemfe_sevilla/settings.py
cocemfe_sevilla/cocemfe_sevilla/urls.py
cocemfe_sevilla/documents/templates/view_pdf.html
cocemfe_sevilla/documents/urls.py
cocemfe_sevilla/professionals/templates/list_chats.html
cocemfe_sevilla/requirements.txt
cocemfe_sevilla/static/css/chat.css

Actualiza chat para que use webscokets. Para probarlo podeís logearos y iros a chats y selleccionar uno. Ahora necesitaréis dos navegadores (Al menos con lo que probe yo) y en cada uno haceis login con usuarios distintos y os  aseguráis de que ambos puedan acceder al mismo chat y empezada mandar mensajes y veis que no hace falta refresh.

feat: Actualiza Chat con websockets

---

Dockerfile
cocemfe_sevilla/cocemfe_sevilla/asgi.py
cocemfe_sevilla/cocemfe_sevilla/settings.py

Añade dockerfile para el contenedor de docker

feat: Añade configuración de docker

---

cocemfe_sevilla/documents/models.py
cocemfe_sevilla/documents/templates/update_pdf.html
cocemfe_sevilla/documents/templates/upload_pdf.html
cocemfe_sevilla/documents/tests.py
cocemfe_sevilla/documents/views.py
cocemfe_sevilla/maps/tests.py
cocemfe_sevilla/maps/views.py

Feat: validación de la localidad de los documentos

---

cocemfe_sevilla/chat_messages/consumers.py
cocemfe_sevilla/chat_messages/templates/chatPage.html
cocemfe_sevilla/chat_messages/views.py
cocemfe_sevilla/static/css/chat.css

Añadido el frontend de Chats.
Para probar crear dos cuentas, un documento y probar a mandar mensajes por el chat con las cuentas abiertas simultáneamente en navegadores distintos. Se debe probar si el usuario tiene imagen de perfil configurada y si no la tiene.

feat: Añadido frontend de chats.

---

cocemfe_sevilla/documents/models.py
cocemfe_sevilla/maps/views.py

hotfix: bug 403 parcheado
